# Generated by Django 2.1.5 on 2019-04-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_usercreate_usernew'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernew',
            name='password2',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
