# Generated by Django 2.1.5 on 2019-04-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_usernew_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernew',
            name='password2',
        ),
    ]
